import os
env = Environment()

env['project_root'] = os.getcwd()
env['project_name'] = "register_factory"

env.SConscript(
    dirs = '.',
    exports = 'env',
    variant_dir = 'build',
    duplicate = 1
)